export const GET_GAMES= 'GET_GAMES'
export const SEARCH= 'SEARCH'
export const DETAIL= 'DETAIL'
export const GET_GENEROS= 'GET_GENEROS'
export const PAGINATE= 'PAGINATE'
export const ORDEN= 'ORDEN'
export const FILTER= 'FILTER'
export const FILTERER= 'FILTERER'
